2021-03-21 10:39:17,370 p=root u=16218 | network_os is set to community.routeros.routeros
2021-03-21 10:39:17,594 p=root u=16206 | router | FAILED | rc=2 >>
[Errno 2] No such file or directory

2021-03-21 10:39:17,695 p=root u=16226 | shutdown complete
2021-03-21 10:39:53,976 p=root u=16483 | network_os is set to community.routeros.routeros
2021-03-21 10:39:54,199 p=root u=16474 | router | FAILED | rc=2 >>
[Errno 2] No such file or directory

2021-03-21 10:39:54,300 p=root u=16488 | shutdown complete
2021-03-21 10:42:16,752 p=root u=17003 | network_os is set to community.routeros.routeros
2021-03-21 10:42:16,970 p=root u=16992 | router | FAILED | rc=2 >>
[Errno 2] No such file or directory

2021-03-21 10:42:17,072 p=root u=17008 | shutdown complete
2021-03-21 10:44:00,770 p=root u=17424 | [WARNING]: Could not match supplied host pattern, ignoring: main.yaml

2021-03-21 10:44:00,770 p=root u=17424 | [WARNING]: No hosts matched, nothing to do

2021-03-21 10:44:00,772 p=root u=17424 | ERROR! No argument passed to command module
2021-03-21 10:44:09,559 p=root u=17468 | PLAY [RouterOS test with network_cli connection] *******************************************************************************************
2021-03-21 10:44:09,566 p=root u=17468 | TASK [community.routeros.command] **********************************************************************************************************
2021-03-21 10:44:09,830 p=root u=17481 | network_os is set to community.routeros.routeros
2021-03-21 10:44:10,081 p=root u=17468 | fatal: [router]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "paramiko is not installed: No module named 'paramiko'"}
2021-03-21 10:44:10,083 p=root u=17468 | PLAY RECAP *********************************************************************************************************************************
2021-03-21 10:44:10,083 p=root u=17468 | router                     : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2021-03-21 10:44:10,182 p=root u=17486 | shutdown complete
2021-03-21 10:46:03,816 p=root u=17945 | PLAY [RouterOS test with network_cli connection] *******************************************************************************************
2021-03-21 10:46:03,824 p=root u=17945 | TASK [community.routeros.command] **********************************************************************************************************
2021-03-21 10:46:04,102 p=root u=17960 | network_os is set to community.routeros.routeros
2021-03-21 10:46:04,361 p=root u=17945 | fatal: [router]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "paramiko is not installed: No module named 'paramiko'"}
2021-03-21 10:46:04,364 p=root u=17945 | PLAY RECAP *********************************************************************************************************************************
2021-03-21 10:46:04,364 p=root u=17945 | router                     : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2021-03-21 10:46:04,464 p=root u=17965 | shutdown complete
2021-03-21 10:48:06,887 p=root u=18505 | PLAY [RouterOS test with network_cli connection] *******************************************************************************************
2021-03-21 10:48:06,894 p=root u=18505 | TASK [community.routeros.command] **********************************************************************************************************
2021-03-21 10:48:07,179 p=root u=18515 | network_os is set to community.routeros.routeros
2021-03-21 10:48:07,461 p=root u=18505 | fatal: [router]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "paramiko is not installed: No module named 'paramiko'"}
2021-03-21 10:48:07,462 p=root u=18505 | PLAY RECAP *********************************************************************************************************************************
2021-03-21 10:48:07,462 p=root u=18505 | router                     : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2021-03-21 10:48:07,562 p=root u=18520 | shutdown complete
2021-03-21 10:48:50,299 p=root u=18742 | PLAY [RouterOS test with network_cli connection] *******************************************************************************************
2021-03-21 10:48:50,307 p=root u=18742 | TASK [community.routeros.command] **********************************************************************************************************
2021-03-21 10:48:50,588 p=root u=18752 | network_os is set to community.routeros.routeros
2021-03-21 10:48:50,988 p=root u=18742 | fatal: [router]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "Invalid/incorrect username/password. Authentication failed."}
2021-03-21 10:48:50,990 p=root u=18742 | PLAY RECAP *********************************************************************************************************************************
2021-03-21 10:48:50,990 p=root u=18742 | router                     : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2021-03-21 10:48:51,090 p=root u=18759 | shutdown complete
2021-03-21 10:49:14,048 p=root u=18887 | PLAY [RouterOS test with network_cli connection] *******************************************************************************************
2021-03-21 10:49:14,055 p=root u=18887 | TASK [community.routeros.command] **********************************************************************************************************
2021-03-21 10:49:14,347 p=root u=18897 | network_os is set to community.routeros.routeros
2021-03-21 10:49:25,169 p=root u=18887 | ok: [router]
2021-03-21 10:49:25,173 p=root u=18887 | TASK [debug] *******************************************************************************************************************************
2021-03-21 10:49:25,458 p=root u=18887 | ok: [router] => {
    "system_resource_print.stdout_lines": [
        [
            "uptime: 6h48m45s",
            "                  version: 6.47.2 (stable)",
            "               build-time: Aug/13/2020 06:39:44",
            "              free-memory: 32.0MiB",
            "             total-memory: 96.0MiB",
            "                      cpu: Intel(R)",
            "                cpu-count: 1",
            "            cpu-frequency: 2712MHz",
            "                 cpu-load: 2%",
            "           free-hdd-space: 21.4MiB",
            "          total-hdd-space: 63.5MiB",
            "  write-sect-since-reboot: 5288",
            "         write-sect-total: 5289",
            "        architecture-name: x86_64",
            "               board-name: CHR",
            "                 platform: MikroTik"
        ]
    ]
}
2021-03-21 10:49:25,461 p=root u=18887 | PLAY RECAP *********************************************************************************************************************************
2021-03-21 10:49:25,461 p=root u=18887 | router                     : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2021-03-21 10:49:25,561 p=root u=18902 | shutdown complete
